# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PassGen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PassGenerator(object):
    def setupUi(self, PassGenerator):
        PassGenerator.setObjectName("PassGenerator")
        PassGenerator.resize(371, 477)
        PassGenerator.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(PassGenerator)
        self.centralwidget.setStyleSheet("color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dropshadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropshadowFrame.setStyleSheet("QFrame{\n"
                                           "border-radius: 8px;\n"
                                           "background-color: rgb(35, 35, 35);\n"
                                           "\n"
                                           "}\n"
                                           "\n"
                                           "")
        self.dropshadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropshadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropshadowFrame.setObjectName("dropshadowFrame")
        self.frame_params = QtWidgets.QFrame(self.dropshadowFrame)
        self.frame_params.setGeometry(QtCore.QRect(10, 140, 331, 231))
        self.frame_params.setStyleSheet("border-radius: 5px;\n"
                                        "background-color: rgb(30, 30, 30);")
        self.frame_params.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_params.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_params.setLineWidth(5)
        self.frame_params.setObjectName("frame_params")
        self.lineEdit_passLength = QtWidgets.QLineEdit(self.frame_params)
        self.lineEdit_passLength.setGeometry(QtCore.QRect(230, 10, 91, 35))
        self.lineEdit_passLength.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_passLength.setFont(font)
        self.lineEdit_passLength.setStyleSheet("QLineEdit {\n"
                                               "    background-color: rgb(25,25,25);\n"
                                               "    border-radius: 5px;\n"
                                               "    border: 2px solid rgb(60, 60, 60);\n"
                                               "    padding-left: 10px;\n"
                                               "}\n"
                                               "QLineEdit:hover {\n"
                                               "    border: 2px solid rgb(40, 40, 40);\n"
                                               "}\n"
                                               "QLineEdit:focus {\n"
                                               "    border: 2px solid rgb(90, 90, 90);\n"
                                               "}")
        self.lineEdit_passLength.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_passLength.setText("")
        self.lineEdit_passLength.setMaxLength(2)
        self.lineEdit_passLength.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_passLength.setPlaceholderText("")
        self.lineEdit_passLength.setObjectName("lineEdit_passLength")
        self.layoutWidget = QtWidgets.QWidget(self.frame_params)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 311, 175))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 7, 10, -1)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_uc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_uc.setFont(font)
        self.label_uc.setStyleSheet("background-color:transparent")
        self.label_uc.setObjectName("label_uc")
        self.horizontalLayout_2.addWidget(self.label_uc)
        self.checkBox_uppercase = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_uppercase.setFont(font)
        self.checkBox_uppercase.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_uppercase.setAutoFillBackground(False)
        self.checkBox_uppercase.setStyleSheet("\n"
                                              "QCheckBox::indicator {\n"
                                              "    border: 3px solid rgb(80, 80, 80);\n"
                                              "    width: 15px;\n"
                                              "    height: 15px;\n"
                                              "    border-radius: 10px;\n"
                                              "    background: rgb(44, 49, 60);\n"
                                              "}\n"
                                              "QCheckBox::indicator:hover {\n"
                                              "    border: 3px solid rgb(58, 66, 81);\n"
                                              "}\n"
                                              "QCheckBox::indicator:checked {\n"
                                              "    background: 3px solid rgb(52, 59, 72);\n"
                                              "    border: 3px solid rgb(52, 59, 72);    \n"
                                              "    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
                                              "}\n"
                                              "")
        self.checkBox_uppercase.setText("")
        self.checkBox_uppercase.setIconSize(QtCore.QSize(5, 20))
        self.checkBox_uppercase.setObjectName("checkBox_uppercase")
        self.horizontalLayout_2.addWidget(self.checkBox_uppercase)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 7, 10, -1)
        self.horizontalLayout_4.setSpacing(50)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_lc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_lc.setFont(font)
        self.label_lc.setStyleSheet("background-color:transparent")
        self.label_lc.setObjectName("label_lc")
        self.horizontalLayout_4.addWidget(self.label_lc)
        self.checkBox_lowercase = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_lowercase.setFont(font)
        self.checkBox_lowercase.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_lowercase.setAutoFillBackground(False)
        self.checkBox_lowercase.setStyleSheet("\n"
                                              "QCheckBox::indicator {\n"
                                              "    border: 3px solid rgb(80, 80, 80);\n"
                                              "    width: 15px;\n"
                                              "    height: 15px;\n"
                                              "    border-radius: 10px;\n"
                                              "    background: rgb(44, 49, 60);\n"
                                              "}\n"
                                              "QCheckBox::indicator:hover {\n"
                                              "    border: 3px solid rgb(58, 66, 81);\n"
                                              "}\n"
                                              "QCheckBox::indicator:checked {\n"
                                              "    background: 3px solid rgb(52, 59, 72);\n"
                                              "    border: 3px solid rgb(52, 59, 72);    \n"
                                              "    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
                                              "}\n"
                                              "")
        self.checkBox_lowercase.setText("")
        self.checkBox_lowercase.setIconSize(QtCore.QSize(5, 20))
        self.checkBox_lowercase.setObjectName("checkBox_lowercase")
        self.horizontalLayout_4.addWidget(self.checkBox_lowercase)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(7, 7, 10, -1)
        self.horizontalLayout_6.setSpacing(50)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_num = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_num.setFont(font)
        self.label_num.setStyleSheet("background-color:transparent")
        self.label_num.setObjectName("label_num")
        self.horizontalLayout_6.addWidget(self.label_num)
        self.checkBox_numbers = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_numbers.setFont(font)
        self.checkBox_numbers.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_numbers.setAutoFillBackground(False)
        self.checkBox_numbers.setStyleSheet("\n"
                                            "QCheckBox::indicator {\n"
                                            "    border: 3px solid rgb(80, 80, 80);\n"
                                            "    width: 15px;\n"
                                            "    height: 15px;\n"
                                            "    border-radius: 10px;\n"
                                            "    background: rgb(44, 49, 60);\n"
                                            "}\n"
                                            "QCheckBox::indicator:hover {\n"
                                            "    border: 3px solid rgb(58, 66, 81);\n"
                                            "}\n"
                                            "QCheckBox::indicator:checked {\n"
                                            "    background: 3px solid rgb(52, 59, 72);\n"
                                            "    border: 3px solid rgb(52, 59, 72);    \n"
                                            "    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
                                            "}\n"
                                            "")
        self.checkBox_numbers.setText("")
        self.checkBox_numbers.setIconSize(QtCore.QSize(5, 20))
        self.checkBox_numbers.setObjectName("checkBox_numbers")
        self.horizontalLayout_6.addWidget(self.checkBox_numbers)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(7, 7, 10, -1)
        self.horizontalLayout_5.setSpacing(50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_sym = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_sym.setFont(font)
        self.label_sym.setStyleSheet("background-color:transparent")
        self.label_sym.setObjectName("label_sym")
        self.horizontalLayout_5.addWidget(self.label_sym)
        self.checkBox_symbols = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_symbols.setFont(font)
        self.checkBox_symbols.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_symbols.setAutoFillBackground(False)
        self.checkBox_symbols.setStyleSheet("\n"
                                            "QCheckBox::indicator {\n"
                                            "    border: 3px solid rgb(80, 80, 80);\n"
                                            "    width: 15px;\n"
                                            "    height: 15px;\n"
                                            "    border-radius: 10px;\n"
                                            "    background: rgb(44, 49, 60);\n"
                                            "}\n"
                                            "QCheckBox::indicator:hover {\n"
                                            "    border: 3px solid rgb(58, 66, 81);\n"
                                            "}\n"
                                            "QCheckBox::indicator:checked {\n"
                                            "    background: 3px solid rgb(52, 59, 72);\n"
                                            "    border: 3px solid rgb(52, 59, 72);    \n"
                                            "    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
                                            "}\n"
                                            "")
        self.checkBox_symbols.setText("")
        self.checkBox_symbols.setIconSize(QtCore.QSize(5, 20))
        self.checkBox_symbols.setObjectName("checkBox_symbols")
        self.horizontalLayout_5.addWidget(self.checkBox_symbols)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_passLength = QtWidgets.QLabel(self.frame_params)
        self.label_passLength.setGeometry(QtCore.QRect(16, 10, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_passLength.setFont(font)
        self.label_passLength.setStyleSheet("background-color:transparent")
        self.label_passLength.setObjectName("label_passLength")
        self.generated_password = QtWidgets.QLabel(self.dropshadowFrame)
        self.generated_password.setGeometry(QtCore.QRect(10, 70, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generated_password.sizePolicy().hasHeightForWidth())
        self.generated_password.setSizePolicy(sizePolicy)
        self.generated_password.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.generated_password.setFont(font)
        self.generated_password.setStyleSheet("QLabel{\n"
                                              "color: rgb(98, 103, 111);\n"
                                              "background-color: rgb(20, 20, 20);\n"
                                              "}")
        self.generated_password.setFrameShape(QtWidgets.QFrame.Panel)
        self.generated_password.setFrameShadow(QtWidgets.QFrame.Raised)
        self.generated_password.setLineWidth(4)
        self.generated_password.setText("")
        self.generated_password.setTextFormat(QtCore.Qt.AutoText)
        self.generated_password.setScaledContents(False)
        self.generated_password.setAlignment(QtCore.Qt.AlignCenter)
        self.generated_password.setWordWrap(True)
        self.generated_password.setIndent(0)
        self.generated_password.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.generated_password.setObjectName("generated_password")
        self.button_generate_password = QtWidgets.QPushButton(self.dropshadowFrame)
        self.button_generate_password.setGeometry(QtCore.QRect(10, 400, 161, 41))
        self.button_generate_password.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.button_generate_password.setFont(font)
        self.button_generate_password.setStyleSheet("QPushButton {\n"
                                                    "    border: 2px solid rgb(28, 28, 28);\n"
                                                    "    border-radius: 3px;\n"
                                                    "    background-color: rgb(30, 30, 30);\n"
                                                    "}\n"
                                                    "QPushButton:hover {\n"
                                                    "    background-color: rgb(35, 35, 35);\n"
                                                    "}\n"
                                                    "QPushButton:pressed {    \n"
                                                    "    background-color: rgb(22, 22, 22);\n"
                                                    "    border: 2px solid rgb(28, 28, 28);\n"
                                                    "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/24x24/pass_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_generate_password.setIcon(icon)
        self.button_generate_password.setIconSize(QtCore.QSize(25, 25))
        self.button_generate_password.setObjectName("button_generate_password")
        self.window_close_button = QtWidgets.QPushButton(self.dropshadowFrame)
        self.window_close_button.setGeometry(QtCore.QRect(308, 12, 31, 28))
        self.window_close_button.setStyleSheet("QPushButton {\n"
                                               "    border: 2px solid rgb(28, 28, 28);\n"
                                               "    border-radius: 3px;\n"
                                               "    background-color: rgb(30, 30, 30);\n"
                                               "}\n"
                                               "QPushButton:hover {\n"
                                               "    background-color: rgb(35, 35, 35);\n"
                                               "}\n"
                                               "QPushButton:pressed {    \n"
                                               "    background-color: rgb(22, 22, 22);\n"
                                               "    border: 2px solid rgb(28, 28, 28);\n"
                                               "}")
        self.window_close_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/24x24/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.window_close_button.setIcon(icon1)
        self.window_close_button.setIconSize(QtCore.QSize(16, 16))
        self.window_close_button.setObjectName("window_close_button")
        self.button_copy_password = QtWidgets.QPushButton(self.dropshadowFrame)
        self.button_copy_password.setGeometry(QtCore.QRect(180, 400, 161, 41))
        self.button_copy_password.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.button_copy_password.setFont(font)
        self.button_copy_password.setStyleSheet("QPushButton {\n"
                                                "    border: 2px solid rgb(28, 28, 28);\n"
                                                "    border-radius: 3px;\n"
                                                "    background-color: rgb(30, 30, 30);\n"
                                                "}\n"
                                                "QPushButton:hover {\n"
                                                "    background-color: rgb(35, 35, 35);\n"
                                                "}\n"
                                                "QPushButton:pressed {    \n"
                                                "    background-color: rgb(22, 22, 22);\n"
                                                "    border: 2px solid rgb(28, 28, 28);\n"
                                                "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/24x24/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_copy_password.setIcon(icon2)
        self.button_copy_password.setIconSize(QtCore.QSize(22, 22))
        self.button_copy_password.setObjectName("button_copy_password")
        self.label_main = QtWidgets.QLabel(self.dropshadowFrame)
        self.label_main.setGeometry(QtCore.QRect(15, 20, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_main.setFont(font)
        self.label_main.setObjectName("label_main")
        self.horizontalLayout.addWidget(self.dropshadowFrame)
        PassGenerator.setCentralWidget(self.centralwidget)

        self.retranslateUi(PassGenerator)
        QtCore.QMetaObject.connectSlotsByName(PassGenerator)

    def retranslateUi(self, PassGenerator):
        _translate = QtCore.QCoreApplication.translate
        PassGenerator.setWindowTitle(_translate("PassGenerator", "MainWindow"))
        self.label_uc.setText(_translate("PassGenerator", "Include uppercase letters"))
        self.label_lc.setText(_translate("PassGenerator", "Include lowercase letters"))
        self.label_num.setText(_translate("PassGenerator", "Include numbers"))
        self.label_sym.setText(_translate("PassGenerator", "Include symbols"))
        self.label_passLength.setText(_translate("PassGenerator", "Password Length"))
        self.button_generate_password.setText(_translate("PassGenerator", " Generate"))
        self.button_copy_password.setText(_translate("PassGenerator", " Copy"))
        self.label_main.setText(_translate("PassGenerator", "Password Generator"))


import files_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    PassGenerator = QtWidgets.QMainWindow()
    ui = Ui_PassGenerator()
    ui.setupUi(PassGenerator)
    PassGenerator.show()
    sys.exit(app.exec_())
