# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passgen_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 229)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame_maindialog = QtWidgets.QFrame(Dialog)
        self.frame_maindialog.setGeometry(QtCore.QRect(10, 10, 491, 211))
        self.frame_maindialog.setStyleSheet("background-color: rgb(35, 35, 35);\n"
                                            "border-radius: 10px;")
        self.frame_maindialog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_maindialog.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_maindialog.setObjectName("frame_maindialog")
        self.verticalFrame = QtWidgets.QFrame(self.frame_maindialog)
        self.verticalFrame.setGeometry(QtCore.QRect(0, -1, 491, 141))
        self.verticalFrame.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top_btns = QtWidgets.QFrame(self.verticalFrame)
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_top_btns.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                          "border-radius: 5px;")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_top.sizePolicy().hasHeightForWidth())
        self.frame_label_top.setSizePolicy(sizePolicy)
        self.frame_label_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top.setObjectName("frame_label_top")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_label_top)
        self.horizontalLayout_10.setContentsMargins(5, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.button_status_indicator = QtWidgets.QPushButton(self.frame_label_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_status_indicator.sizePolicy().hasHeightForWidth())
        self.button_status_indicator.setSizePolicy(sizePolicy)
        self.button_status_indicator.setMaximumSize(QtCore.QSize(30, 30))
        self.button_status_indicator.setStyleSheet("QPushButton {\n"
                                                   "    border-radius: 5px;    \n"
                                                   "    background-color: transparent;\n"
                                                   "}")
        self.button_status_indicator.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/24x24/pass_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_status_indicator.setIcon(icon)
        self.button_status_indicator.setIconSize(QtCore.QSize(24, 24))
        self.button_status_indicator.setObjectName("button_status_indicator")
        self.horizontalLayout_10.addWidget(self.button_status_indicator)
        self.label_title_bar = QtWidgets.QLabel(self.frame_label_top)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar.setFont(font)
        self.label_title_bar.setStyleSheet("background: transparent;\n"
                                           "color:white\n"
                                           "")
        self.label_title_bar.setObjectName("label_title_bar")
        self.horizontalLayout_10.addWidget(self.label_title_bar)
        self.horizontalLayout_4.addWidget(self.frame_label_top)
        self.frame_closebutton = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_closebutton.sizePolicy().hasHeightForWidth())
        self.frame_closebutton.setSizePolicy(sizePolicy)
        self.frame_closebutton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_closebutton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_closebutton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_closebutton.setObjectName("frame_closebutton")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_closebutton)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_closedialog = QtWidgets.QPushButton(self.frame_closebutton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_closedialog.sizePolicy().hasHeightForWidth())
        self.button_closedialog.setSizePolicy(sizePolicy)
        self.button_closedialog.setMinimumSize(QtCore.QSize(40, 0))
        self.button_closedialog.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_closedialog.setStyleSheet("QPushButton {    \n"
                                              "    border: none;\n"
                                              "    background-color: transparent;\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "    background-color: rgb(52, 59, 72);\n"
                                              "}\n"
                                              "QPushButton:pressed {    \n"
                                              "    background-color: rgb(85, 170, 255);\n"
                                              "}")
        self.button_closedialog.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_closedialog.setIcon(icon1)
        self.button_closedialog.setObjectName("button_closedialog")
        self.horizontalLayout_5.addWidget(self.button_closedialog)
        self.horizontalLayout_4.addWidget(self.frame_closebutton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_top_btns)
        self.line = QtWidgets.QFrame(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setStyleSheet("background-color: rgb(170, 170, 255);\n"
                                "border-radius:10px;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_message = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_message.setFont(font)
        self.label_message.setStyleSheet("color:white;\n"
                                         "")
        self.label_message.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_message.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_message.setWordWrap(True)
        self.label_message.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.label_message.setObjectName("label_message")
        self.verticalLayout.addWidget(self.label_message)
        self.pushButton_ok = QtWidgets.QPushButton(self.frame_maindialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(350, 150, 121, 39))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ok.sizePolicy().hasHeightForWidth())
        self.pushButton_ok.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setStyleSheet("QPushButton {\n"
                                         "    color:white;\n"
                                         "    border: 2px solid rgb(28, 28, 28);\n"
                                         "    border-radius: 3px;\n"
                                         "    background-color: rgb(30, 30, 30);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "color:white;\n"
                                         "background-color: rgb(35, 35, 35);\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "color:white;\n"
                                         "    background-color: rgb(22, 22, 22);\n"
                                         "    border: 2px solid rgb(28, 28, 28);\n"
                                         "}")
        self.pushButton_ok.setObjectName("pushButton_ok")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title_bar.setText(_translate("Dialog", "Uh-Oh!"))
        self.button_closedialog.setToolTip(_translate("Dialog", "Close"))
        self.label_message.setText(
            _translate("Dialog", "The length of the password should be greater than 4 and should not exceed more than 40 "
                                 "characters"))
        self.pushButton_ok.setText(_translate("Dialog", "Ok"))


import files_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
